---
- hosts: webservers
  become_user: root
  become: yes
  gather_facts: false

  tasks:

  - name: Create app directory if not exist
    file:
      state: directory
      path: '{{deploy_dir}}'
      owner: root
      group: root
      mode: 0755

  - name: Fetch repo from Git
    git:
      repo: '{{git_repo_url}}'
      dest: '{{deploy_dir}}'
      version: '{{release}}'

  - name: Restart apache server
    command: service httpd restart
